repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
  - id: mypy
    additional_dependencies:
    - click
    - iam-units
    - Jinja2
    - lxml-stubs
    - pandas-stubs
    - Pint
    - plotnine
    - pycountry
    - pytest
    - sdmx1
    - traitlets
    - types-PyYAML
    - types-python-dateutil
    - types-requests
    - xarray
    args: []
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.0
  hooks:
  - id: ruff
  - id: ruff-format
    args: [ --check ]
