name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    continue-on-error: true

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: $HOME/.cache/pip
        key: ubuntu-latest

    - name: Upgrade pip, wheel
      run: python -m pip install --upgrade pip wheel

    - name: Check "black" code style
      run: |
         pip install black
         black --check .

    # TODO add mypy

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --count --max-complexity=15 --show-source --statistics

    - name: Build package
      run: |
        pip install twine wheel
        python3 setup.py bdist_wheel sdist
        twine check dist/*

    - name: Build documentation using Sphinx
      run: |
        pip install .[doc]
        make --directory=doc html
